stages:          # List of stages for jobs, and their order of execution
  - build
  - test

before_script:
  - echo "Running global before_script"
#  - mkdir -p bin # intentionally inserted to skip cloning of private repos
#  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lukevassallo.com/luke/KicadParser --recurse-submodules bin/KicadParser
#  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lukevassallo.com/luke/SA_PCB --recurse-submodules bin/SA_PCB
#  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lukevassallo.com/luke/pcbRouter --recurse-submodules bin/pcbRouter
  - git config --global credential.helper store
  - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lukevassallo.com" > ~/.git-credentials
  - ./install_tools_and_virtual_environment.sh

after_script:
#  - source setup.sh
  - ./clean.sh

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - general-purpose, gpu-enabled
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo "Compiling the code..."
    - source setup.sh
    - echo ${RL_PCB}
    - ls -alh
    - echo "Compile complete."

system-test-gpu:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - general-purpose, gpu-enabled
  before_script:
    - echo "Running local before_script"
    - mkdir -p bin # intentionally inserted to skip cloning of private repos
    - ./install_tools_and_virtual_environment.sh
  variables:
    GIT_STRATEGY: fetch
  timeout: 12h 0m
  script:
    - source setup.sh
    - echo ${RL_PCB}
    - cd ${RL_PCB}/tests/05_training_td3_cuda_fast/
    - ./run.sh
  artifacts:
    paths:
      - ./tests/05_training_td3_cuda_fast/work/
      - ./tests/05_training_td3_cuda_fast/experiment_report.pdf

system-test-cpu:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - general-purpose, gpu-enabled
  before_script:
    - echo "Running local before_script"
    - mkdir -p bin # intentionally inserted to skip cloning of private repos
    - ./install_tools_and_virtual_environment.sh --cpu_only
  variables:
    GIT_STRATEGY: fetch
  timeout: 12h 0m
  script:
    - source setup.sh
    - echo ${RL_PCB}
    - cd ${RL_PCB}/tests/06_training_td3_cpu_fast/
    - ./run.sh
  artifacts:
    paths:
      - ./tests/06_training_td3_cpu_fast/work/
      - ./tests/06_training_td3_cpu_fast/experiment_report.pdf
